/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memory;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.HashMap;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JPanel;

/**
 *
 * @author syl-b
 */
public class MainFrame extends javax.swing.JFrame {

    //Hash map of number
    HashMap<String, String> map = new HashMap<String, String>();

    /**
     * load pictures in hashmap
     * @author Théo
     */
    public void loadPictures(int numberOfCard) {
        
        for (int i = 0; i < numberOfCard; i++) {
            
            Random rand = new Random();

            // Obtain a number between [0 - numberOfCard-1 ].
            int n = rand.nextInt(numberOfCard);
            
            
            
            //put a String in hashmap(composition: Numéro i) where i is the hashmap's size
            int mapSize = map.size();
            String text = "Numéro " + i;
            map.put(String.valueOf(mapSize), text);
        }//End for
    }//end loadPictures

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        int rows = 4;
        int cols = 1;
        int hgap = 0;
        int vgap = 0;

        this.setLayout(new BorderLayout());

        GridLayout GridMemory = new GridLayout(rows, cols);

        pnlGrid = new JPanel();
        pnlConf = new JPanel();

        this.add(pnlConf, BorderLayout.SOUTH);
        this.add(pnlGrid, BorderLayout.CENTER);
        this.setBounds(100, 100, 800, 600);
        pnlGrid.setLayout(GridMemory);

        //this.setContentPane(pnlMemory);
        pnlGrid.add(new JButton("1"));
        pnlGrid.add(new JButton("2"));
        pnlConf.add(new JButton("Calculer"));
        pnlConf.setLayout(new FlowLayout(FlowLayout.LEFT));
        pnlGrid.add(new JButton("4"));
        pnlGrid.add(new JButton("4"));
        pnlGrid.add(new JButton("4"));
        pnlGrid.add(new JButton("4"));
        pnlGrid.add(new JButton("4"));
        pnlGrid.add(new JButton("4"));
        pnlGrid.add(new JButton("4"));
        pnlGrid.add(new JButton("4"));
        pnlGrid.add(new JButton("4"));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      panel1 = new java.awt.Panel();

      javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
      panel1.setLayout(panel1Layout);
      panel1Layout.setHorizontalGroup(
         panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 100, Short.MAX_VALUE)
      );
      panel1Layout.setVerticalGroup(
         panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 100, Short.MAX_VALUE)
      );

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 683, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGap(0, 426, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);

            }
        });
    }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private java.awt.Panel panel1;
   // End of variables declaration//GEN-END:variables
   private JPanel pnlGrid;
    private JPanel pnlConf;
}
